title: Joyce Onyango
description: Data professional building insights with spatial intelligence

url: https://jdaonyango.github.io
baseurl: ""

remote_theme: chrisbobbe/jekyll-theme-prologue

collections: [sections]

avatar: assets/images/avatar.jpg

cover-photo: assets/images/banner.jpg
cover-photo-alt: Nairobi skyline at sunset